### ISSUE TITLE
Security vulnerablity: Passwords stored in plaintext.

### ISSUE THREAD

**Issue by lyallstewart** [lyallstewart/A-Level-NEA-Projects#26]
Pretty self-explanitory tbh :)

**Comment by 48panda48** [comment]
When we have a basic login, i will work in this

**Comment by lyallstewart** [comment]
So we haven't even stored any passwords yet, nor do we have the db entries to store them and we've already got this:
![image](https://user-images.githubusercontent.com/78568904/126064292-651fdce7-d8f3-4b4a-bcf2-cb62ffbd0491.png)
