### ISSUE TITLE
 DeprecationWarning: collection.ensureIndex is deprecated

### ISSUE THREAD

**Issue by lyallstewart** [lyallstewart/A-Level-NEA-Projects#37]
We aren't actually calling this anywhere but Node seems to think it's in our code so 🤷 .

**Comment by lyallstewart** [comment]
Not sure we actually can fix this so...

**Comment by 48panda48** [comment]
even if we run --trace-deprecation the stack doesn't mention our code anywhere

**Comment by lyallstewart** [comment]
So while it might technically be fixable, it would mean changing a packages code which we cannot do, at least not without the risk of breaking everything.

Seeing as it's not our code, it's not worth fixing.
