### ISSUE TITLE
TypeError: onChange is not a function

### ISSUE THREAD

**Issue by 48panda48** [lyallstewart/A-Level-NEA-Projects#41]
If we put the app into strict mode we get 15 of these errors

**Comment by lyallstewart** [comment]
The only solution would be to edit the module's source code

**Comment by lyallstewart** [comment]
Which is not ideal

**Comment by lyallstewart** [comment]
Module replaced with non-broken one

**Comment by 48panda48** [comment]
Dear other devs, please say your node module is in typescript
